# rplidar_params.yaml
#
# Copyright (C) 2016 Alessandro Francescon
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# The serial port RPLidar is connected to (default: /dev/ttymxc4)
serial_port: /dev/ttymxc4

# The frame laser data are referred (default: base_laser)
frame_id: base_laser

# The diagnostics update frequency in Hz (default: 1.0)
diagnostics_frequency: 1.0
